name: Shivam Gupta
permalink: :year/:month/:day/:title
baseurl: /

# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email : shivam.gupta@blackfigtech.com
  github : shivam-bft

# Links in the navigation, you can modify both link name and link url
nav:
   Home: "/"
   
markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed
